### ISSUE TITLE
Add documentation for using typesVersions when experiencing issues with multiple entrypoints

### ISSUE THREAD

**Issue by dsherret** [denoland/dnt#118]
TypeScript seems a little broken at the moment WRT package.json exports: https://github.com/microsoft/TypeScript/issues/33079

I think probably there should be some documentation update about using `typesVersions` because it seems like using `exports` in package.json is not enough in all cases. I'm not sure if it's worth it to have dnt automatically generate this `typesVersions` workaround at the moment.

**Comment by DerZade** [comment]
I just wanted to open a similar issue myself.

I just wasted two hours to realize that TS still doesn't support exports in package.json. I'm still trying to figuring out the workaround with `typesVersions` and haven't got it work work 100% yet. 🤦‍♂️ 

In any case documentation would be much appreciated (and imho almost necessary), because this is a problem which probably a lot of users will run into. 
Auto-generations of `typesVersion` on top of that would be absolutely amazing. Seems like proper export support will land in TS 4.7, so by setting a version of `<4.7` this would even be fully compatible with newer versions. (also making that version configurable would be nice too)

**Comment by DerZade** [comment]
**For anyone stumbling upon and this having similar issues.**

Here's a quick config, which includes a couple of different paths:
```ts

await build({
    entryPoints: [
        {
            name: '.',
            path: './mod.ts'
        },
        {
            name: './module2',
            path: './module2.ts'
        },
        {
            name: './nested/module3',
            path: './nested/module3.ts'
        },
        {
            name: './nested/module4',
            path: './nested/module4/mod.ts'
        }
    ],
    // [...]
    package: {
        // [...]
        typesVersions: {
            '<4.7': { // Maybe this won't be correct in the future (use "*" to apply for all TS versions)
                'index.d.ts': [
                    'types/mod.d.ts'
                ],
                'module2': [
                    'types/module2.d.ts'
                ],
                'nested/module3': [
                    'types/nested/module3.d.ts'
                ],
                'nested/module4': [
                    'types/nested/module4/mod.d.ts'
                ],
            }
        }
    },
});
```

You could achieve a shorter solution, by using wildcards, but I would **advice against that**. There could be situations, where TS shows a module as existing, but node wouldn't be able to load the module, because it is not listed within the `exports` field of the package.json.

---

_(I hope I'll find time to open a PR for proper docs soon)_
