### ISSUE TITLE
Support inlining sources

### ISSUE THREAD

**Issue by zandaqo** [denoland/dnt#19]
Setting `{ sourceMap: true, inlineSources: true }` for `tsc` creates source map files with inlined sources (which is not the same as the currently used `inlineSourceMap` option), as a result, we don't need to ship source files in a package. Nothing terribly important, but does reduce the amount of files shipped and it would be nice to have such option in `dnt`.

**Comment by dsherret** [comment]
Done in #20. Just note that if the end result is a hybrid package (the default where it creates an ESM and CommonJS package) then you probably don't want to turn this on because it will duplicate the source text in both the esm and commonjs output instead of only distributing it once.

I'll do a release soon. I want to get a few more things in first.
