### ISSUE TITLE
Add instructions showing how to use OTPs when publishing to npm

### ISSUE THREAD

**Issue by bebraw** [denoland/dnt#29]
To improve security, it's a recommended practice to use two-way auth when publishing to npm.

I discovered https://github.com/mmarchini-oss/npm-otp-publish but it's to entirely clear how to connect that with the current recipe at the readme. Another good one to show would be to include GitHub release and change log generation through actions.

Thanks a lot for the tool, it has been very useful already!

**Comment by dsherret** [comment]
Thanks for the recommendation! I believe the solution here is to use an [npm automation token](https://github.blog/changelog/2020-10-02-npm-automation-tokens/) and the docs were missing instructions on how to create one. I added instructions in #32.

**Comment by bebraw** [comment]
@dsherret Thanks. It's probably worth explaining the workflow from Git point of view as well. I.e. which commands to use when publishing.

I set up a fairly complex script that's building the site and the package at https://github.com/bebraw/dragjs/blob/master/.github/workflows/ci.yml but it doesn't seem to find the tag so I suspect I'm doing something wrong at the Git side since it never gets to the parts depending on a tag.

**Comment by dsherret** [comment]
@bebraw thanks for that feedback as well. I added another step in that PR.

For this, it depends on the scenario. In your case, the issue is that it was only running on push to master:

https://github.com/bebraw/dragjs/blob/97abbac8cab6928dacb07158a01a4938b4155671/.github/workflows/ci.yml#L3-L6

See here for a potential solution: https://stackoverflow.com/a/61892639/188246
