### ISSUE TITLE
Why does dnt have to output native ESM code if CJS can be imported from ESM?

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/dnt#386]
`dnt` outputs two directories of files: one of them with ESM and one of them with CJS. It then uses conditional exports in order to expose the right modules in the right situation.

This means that all code and type definitions are shipped twice.

You can import CJS from ESM.

In my naïve mind, `dnt` could just output a single ESM file that simply re-exports everything from the CJS build.

What am I missing here? (Feels like a bit of a dumb question to me, not sure if it is.)

I would be happy to hear about a remote edge case where re-exporting CJS is not a solution. Are there tools that don't work with this?

**Comment by wojpawlik** [comment]
There is no point in ESM that just re-exports CJS. If we can just `import` CJS, so can library users.

> type definitions are shipped twice.

False. They're equivalent, and so conditional exports only have one `"types"` slot.

Related: https://github.com/denoland/dnt/issues/261#issuecomment-1637874858

**Comment by KnorpelSenf** [comment]
> There is no point in ESM that just re-exports CJS. If we can just `import` CJS, so can library users.

Even better. That just makes the question more relevant.

> > type definitions are shipped twice.
> 
> False. They're equivalent, and so conditional exports only have one `"types"` slot.

That's not the behaviour I observe when I build my library with `dnt`. Was this changed at some point?

Check this out: https://www.npmjs.com/package/o-son?activeTab=code

**Comment by 0f-0b** [comment]
`dnt` has to emit ESM if the module uses top-level await. ESM is also easier to statically analyze so [tree-shaking](https://rollupjs.org/introduction/#tree-shaking) works.

Node.js will soon support [importing ESM from CJS synchronously](https://github.com/nodejs/node/commit/5f7fad26050cd574431e3018a557bc6eae5ff716), at which time there would be no reason to output CJS except for compatibility with older tooling.

**Comment by dsherret** [comment]
There's no point in re-exporting the CJS from an ES module. At that point you might as well only ship CJS. To only ship CJS, you can set the `esModule` option to `false` (https://github.com/denoland/dnt/blob/2d1d120df7f110c510c6d2aa07e9d0886855e182/mod.ts#L83-L86)

Type definitions are generated per module kind because it's what the TypeScript team recommends. You can change it to output a single declaration file by setting `declaration` to `separate` (https://github.com/denoland/dnt/blob/2d1d120df7f110c510c6d2aa07e9d0886855e182/mod.ts#L65-L75), but then your library will fail on https://arethetypeswrong.github.io/ and I believe the declaration maps won't be correct.

Once Node allows importing ES modules from CJS the case for dual publishing will mostly go away and shipping just ESM will make sense. At the moment, I've found some slight speedup at runtime by shipping a dual package in an ES project and it lead to a cleaner output when bundling, but it's situational so YMMV.

**Comment by KnorpelSenf** [comment]
Thanks for the answers!
