### ISSUE TITLE
automatic entry points

### ISSUE THREAD

**Issue by mfulton26** [denoland/dnt#42]
I like how in Deno there is a convention that anything that starts with "\_" is considered private and shouldn't be imported. I think it would be helpful to automatically generate entry points for all files not starting with "\_". This might be an opt-in feature but I think it could be enabled by default and be an opt-out feature instead. There's also [subpath patterns](https://nodejs.org/docs/latest-v16.x/api/packages.html#subpath-patterns) but even if that were support by `dnt` I don't think there is a way to specify a "not" in the pattern to exclude things starting with "_".

**Comment by dsherret** [comment]
Some people might not be following this convention. I think it's better for people to be explicit about what entrypoints they want to reduce the amount of magic going on.

That said, perhaps there could be a way to generate an `EntryPoint[]` array from a directory. Maybe something like:

```ts
await build({
  entryPoints: await getDirEntryPoints("."),
  // etc...
});
```

I'd rather not maintain this helper at the current time though because things might still change a lot. I'll re-evaluate once this module is more stable.
