### ISSUE TITLE
`// @ts-` comments are lost while transpiling

### ISSUE THREAD

**Issue by mkrnavana** [denoland/dnt#45]
This causes type errors in the built umd/esm packages where the d.ts is missing `// @ts-expect-error` or `// @ts-ignore` comments from the source.

**Comment by dsherret** [comment]
@mkrnavana could you give an example where this would be useful or give an example of the scenario? There is probably a workaround. I've never heard about using these in declaration files and I'm not sure it would be easily possible to keep those comments because the TS compiler probably doesn't emit them for declaration files.
